name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '26.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: 'build/**/*.{js,css}'
          exclude: 'build/assets/{prerender,release,repos}-*.js'
          strip-hash: '-(.{8})\.'
          minimum-change-threshold: 100
